[build]
  # Build command for the PWA shell
  command = "pnpm install --frozen-lockfile && cd apps/pwa-shell && pnpm build"
  publish = "apps/pwa-shell/out"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"
  
[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.4"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = []}

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "pnpm dev:pwa"
  port = 3000

# Disable automatic Next.js plugin for static export
[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
  disable = true
