# Grahmos V1+V2 Unified - Security Policies Configuration
# Production security policies, compliance, and hardening rules

security:
  # Authentication & Authorization
  authentication:
    jwt:
      algorithm: "RS256"
      expiry: "15m"
      refresh_expiry: "7d"
      issuer: "grahmos-v1v2-unified"
      audience: "grahmos-api"
    
    mfa:
      enabled: true
      methods: ["totp", "backup_codes"]
      grace_period: "30d"
    
    session:
      cookie_secure: true
      cookie_httponly: true
      cookie_samesite: "strict"
      max_age: "1h"
      rotation_interval: "15m"
  
  # Network Security
  network:
    tls:
      min_version: "1.2"
      preferred_version: "1.3"
      cipher_suites:
        - "ECDHE-ECDSA-AES256-GCM-SHA384"
        - "ECDHE-RSA-AES256-GCM-SHA384"
        - "ECDHE-ECDSA-CHACHA20-POLY1305"
        - "ECDHE-RSA-CHACHA20-POLY1305"
      hsts:
        max_age: "31536000"
        include_subdomains: true
        preload: true
    
    cors:
      allowed_origins:
        - "https://yourdomain.com"
        - "https://app.yourdomain.com"
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
      allowed_headers: ["Content-Type", "Authorization", "X-Requested-With"]
      credentials: true
      max_age: "86400"
    
    rate_limiting:
      global:
        window: "15m"
        max_requests: 1000
      auth:
        window: "5m"
        max_requests: 5
      api:
        window: "1m"
        max_requests: 60
  
  # Data Protection
  data_protection:
    encryption:
      at_rest:
        algorithm: "AES-256-GCM"
        key_rotation: "90d"
      in_transit:
        enforce_tls: true
        min_tls_version: "1.2"
      
    backup:
      encryption_enabled: true
      retention_period: "30d"
      verification_interval: "7d"
    
    pii_handling:
      anonymization: true
      retention_period: "2y"
      deletion_policy: "secure_wipe"
  
  # Container Security
  container:
    runtime:
      read_only_filesystem: true
      no_new_privileges: true
      drop_all_capabilities: true
      non_root_user: true
    
    image:
      signed_images_only: true
      vulnerability_scanning: true
      base_image_updates: "weekly"
      distroless_preferred: true
    
    network:
      disable_inter_container_communication: true
      custom_bridge_network: true
      network_policies_enabled: true
  
  # Logging & Monitoring
  logging:
    security_events:
      failed_authentication: true
      privilege_escalation: true
      unauthorized_access: true
      configuration_changes: true
    
    retention:
      security_logs: "1y"
      audit_logs: "2y"
      application_logs: "30d"
    
    sanitization:
      pii_redaction: true
      credential_masking: true
      ip_anonymization: true
  
  # Compliance
  compliance:
    standards:
      - "SOC2"
      - "GDPR"
      - "OWASP_ASVS_4.0"
    
    controls:
      access_control: "mandatory"
      data_encryption: "mandatory"
      audit_logging: "mandatory"
      vulnerability_management: "mandatory"
      incident_response: "mandatory"
  
  # Incident Response
  incident_response:
    automation:
      auto_block_suspicious_ips: true
      auto_scale_on_ddos: true
      auto_rotate_compromised_secrets: true
    
    alerting:
      channels: ["slack", "email", "pagerduty"]
      severity_levels: ["critical", "high", "medium", "low"]
      escalation_rules: true
    
    playbooks:
      security_breach: true
      data_exposure: true
      service_compromise: true
      ddos_attack: true

# Security Headers
security_headers:
  strict_transport_security: "max-age=31536000; includeSubDomains; preload"
  content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; font-src 'self'; object-src 'none'; media-src 'self'; frame-src 'none'; base-uri 'self'; form-action 'self'"
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  referrer_policy: "strict-origin-when-cross-origin"
  permissions_policy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
  cross_origin_embedder_policy: "require-corp"
  cross_origin_opener_policy: "same-origin"
  cross_origin_resource_policy: "same-origin"

# Environment Variables Security
environment_security:
  secrets_management:
    external_secrets_operator: true
    vault_integration: false
    kubernetes_secrets: false
    docker_secrets: true
  
  variable_validation:
    required_vars:
      - "JWT_SECRET_KEY"
      - "ENCRYPTION_KEY" 
      - "DATABASE_PASSWORD"
      - "REDIS_PASSWORD"
      - "GRAFANA_PASSWORD"
    
    pattern_validation:
      passwords: "^.{12,}$"  # Minimum 12 characters
      keys: "^[A-Fa-f0-9]{32,}$"  # Hex keys minimum 32 chars
      urls: "^https://"  # HTTPS only
  
  exposure_prevention:
    log_sanitization: true
    error_message_sanitization: true
    debug_mode_disabled: true
